[Fri Jun 17 11:43:07.491912 2016] [wsgi:error] [pid 3003] [client 80.13.157.88:55380] mod_wsgi (pid=3003): Target WSGI script '/home/web/dojo_env/dojo_entreprises_agiles_env/mon_site/wsgi.py' cannot be loaded as Python module.
[Fri Jun 17 11:43:07.492075 2016] [wsgi:error] [pid 3003] [client 80.13.157.88:55380] mod_wsgi (pid=3003): Exception occurred processing WSGI script '/home/web/dojo_env/dojo_entreprises_agiles_env/mon_site/wsgi.py'.
[Fri Jun 17 11:43:07.492093 2016] [wsgi:error] [pid 3003] [client 80.13.157.88:55380] Traceback (most recent call last):
[Fri Jun 17 11:43:07.492109 2016] [wsgi:error] [pid 3003] [client 80.13.157.88:55380]   File "/home/web/dojo_env/dojo_entreprises_agiles_env/mon_site/wsgi.py", line 12, in <module>
[Fri Jun 17 11:43:07.492155 2016] [wsgi:error] [pid 3003] [client 80.13.157.88:55380]     from django.core.wsgi import get_wsgi_application
[Fri Jun 17 11:43:07.492170 2016] [wsgi:error] [pid 3003] [client 80.13.157.88:55380] ImportError: No module named django.core.wsgi
[Fri Jun 17 12:01:13.865882 2016] [wsgi:error] [pid 3081] [client 80.13.157.88:55956] No WSGI daemon process called 'dojoentreprisesagiles.fr' has been configured: /home/web/dojo_env/dojo_entreprises_agiles_env/mon_site/wsgi.py
[Fri Jun 17 12:01:15.768252 2016] [wsgi:error] [pid 3083] [client 80.13.157.88:55960] No WSGI daemon process called 'dojoentreprisesagiles.fr' has been configured: /home/web/dojo_env/dojo_entreprises_agiles_env/mon_site/wsgi.py
[Fri Jun 17 12:04:07.518785 2016] [wsgi:error] [pid 3084] [client 80.13.157.88:56002] No WSGI daemon process called 'dojoentreprisesagiles.fr' has been configured: /home/web/dojo_env/dojo_entreprises_agiles_env/mon_site/wsgi.py
[Fri Jun 17 12:05:50.668970 2016] [wsgi:error] [pid 3264] /home/web/dojo_env/src/django-timelinejs-master/timelinejs/models.py:5: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
[Fri Jun 17 12:05:50.669035 2016] [wsgi:error] [pid 3264]   class ListField(models.TextField):
[Fri Jun 17 12:05:50.669039 2016] [wsgi:error] [pid 3264] 
[Fri Jun 17 12:05:50.717239 2016] [wsgi:error] [pid 3264] /home/web/dojo_env/dojo_entreprises_agiles_env/mon_site/urls.py:31: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got userena.views.signup). Pass the callable instead.
[Fri Jun 17 12:05:50.717270 2016] [wsgi:error] [pid 3264]   ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
[Fri Jun 17 12:05:50.717273 2016] [wsgi:error] [pid 3264] 
[Fri Jun 17 12:05:50.928456 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/css/bootstrap.min.css
[Fri Jun 17 12:05:50.928490 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:50.928495 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:50.928500 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:50.928504 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:50.928509 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:50.928513 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:50.928518 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:50.928522 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:50.928526 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:50.928530 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:50.932647 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/font-awesome/css/font-awesome.min.css
[Fri Jun 17 12:05:50.932697 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:50.932704 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:50.932709 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:50.932713 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:50.932717 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:50.932721 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:50.932725 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:50.932729 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:50.932732 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:50.932736 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:50.934748 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/css/style.css
[Fri Jun 17 12:05:50.934768 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:50.934773 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:50.934778 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:50.934782 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:50.934786 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:50.934790 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:50.934794 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:50.934798 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:50.934802 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:50.934806 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:51.016420 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.css
[Fri Jun 17 12:05:51.016446 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:51.016450 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:51.016453 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:51.016456 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:51.016459 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:51.016462 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:51.016465 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:51.016467 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:51.016470 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:51.016472 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:51.020696 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/jquery/dist/jquery.min.js
[Fri Jun 17 12:05:51.020716 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:51.020719 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:51.020723 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:51.020725 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:51.020731 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:51.020734 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:51.020737 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:51.020739 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:51.020742 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:51.020745 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:51.023741 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/js/bootstrap.min.js
[Fri Jun 17 12:05:51.023757 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:51.023760 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:51.023763 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:51.023765 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:51.023768 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:51.023771 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:51.023774 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:51.023776 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:51.023778 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:51.023781 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:51.788026 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.js
[Fri Jun 17 12:05:51.788058 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:51.788063 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:51.788068 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:51.788072 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:51.788076 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:51.788080 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:51.788084 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:51.788088 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:51.788105 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:51.788109 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:51.792053 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/script.js
[Fri Jun 17 12:05:51.792075 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:51.792080 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:51.792084 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:51.792088 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:51.792092 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:51.792096 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:51.792100 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:51.792104 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:51.792108 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:51.792111 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:51.795827 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.extras.js
[Fri Jun 17 12:05:51.795853 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:51.795858 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:51.795863 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:51.795867 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:51.795871 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:51.795876 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:51.795880 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:51.795884 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:51.795888 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:51.795892 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:51.799806 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/stickUp2/build/js/stickUp.min.js
[Fri Jun 17 12:05:51.799831 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:51.799835 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:51.799840 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:51.799844 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:51.799848 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:51.799853 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:51.799857 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:51.799876 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:51.799881 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:51.799885 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:52.759551 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/js/bootstrap.min.js
[Fri Jun 17 12:05:52.760831 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:52.760842 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:52.760845 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:52.760847 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:52.760850 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:52.760852 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:52.760855 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:52.760857 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:52.760859 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:52.760861 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:52.766668 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/entete-web (1).png
[Fri Jun 17 12:05:52.766694 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:52.766697 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:52.766699 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:52.766702 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:52.766704 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:52.766707 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:52.766709 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:52.766711 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:52.766713 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:52.766716 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:52.961783 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/stickUp2/build/js/stickUp.min.js
[Fri Jun 17 12:05:52.961808 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:52.961811 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:52.961814 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:52.961816 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:52.961818 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:52.961821 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:52.961835 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:52.961838 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:52.961840 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:52.961842 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:53.038661 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/logoDojoClair.png
[Fri Jun 17 12:05:53.038690 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:53.038693 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:53.038696 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:53.038698 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:53.038700 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:53.038703 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:53.038705 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:53.038707 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:53.038709 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:53.038711 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:53.090950 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/script.js
[Fri Jun 17 12:05:53.090981 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:53.090986 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:53.090990 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:53.090993 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:53.090996 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:53.090999 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:53.091001 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:53.091004 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:53.091006 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:53.091008 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:53.230037 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.js
[Fri Jun 17 12:05:53.230065 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:53.230069 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:53.230072 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:53.230075 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:53.230078 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:53.230114 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:53.230119 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:53.230121 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:53.230124 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:53.230127 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:53.388098 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.extras.js
[Fri Jun 17 12:05:53.388136 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:53.388141 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:53.388145 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:53.388149 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:53.388152 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:53.388156 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:53.388159 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:53.388162 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:53.388165 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:53.388168 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:53.536134 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.css
[Fri Jun 17 12:05:53.536165 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:53.536168 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:53.536171 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:53.536173 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:53.536176 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:53.536178 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:53.536181 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:53.536183 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:53.536185 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:53.536187 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:53.540072 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/entete-web (1).png
[Fri Jun 17 12:05:53.540093 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:53.540096 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:53.540099 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:53.540102 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:53.540117 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:53.540120 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:53.540123 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:53.540125 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:53.540127 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:53.540130 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:05:53.749162 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/logoDojoClair.png
[Fri Jun 17 12:05:53.749204 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:05:53.749211 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:05:53.749216 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:05:53.749221 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:05:53.749226 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:05:53.749230 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:05:53.749235 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:05:53.749240 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:05:53.749244 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:05:53.749249 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:50.777020 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/font-awesome/css/font-awesome.min.css
[Fri Jun 17 12:14:50.777091 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:50.777099 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:50.777103 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:50.777108 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:50.777112 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:50.777116 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:50.777120 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:50.777124 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:50.777129 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:50.777132 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:50.780174 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/jquery/dist/jquery.min.js
[Fri Jun 17 12:14:50.780201 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:50.780206 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:50.780211 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:50.780236 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:50.780242 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:50.780245 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:50.780249 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:50.780253 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:50.780257 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:50.780260 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:50.784321 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/css/bootstrap.min.css
[Fri Jun 17 12:14:50.784347 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:50.784353 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:50.784357 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:50.784360 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:50.784364 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:50.784368 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:50.784372 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:50.784375 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:50.784378 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:50.784382 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:50.787972 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/js/bootstrap.min.js
[Fri Jun 17 12:14:50.787999 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:50.788004 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:50.788008 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:50.788012 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:50.788016 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:50.788020 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:50.788024 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:50.788028 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:50.788032 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:50.788035 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:50.791969 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/stickUp2/build/js/stickUp.min.js
[Fri Jun 17 12:14:50.792001 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:50.792006 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:50.792028 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:50.792032 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:50.792036 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:50.792041 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:50.792045 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:50.792048 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:50.792052 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:50.792056 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:50.796015 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/css/style.css
[Fri Jun 17 12:14:50.796044 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:50.796048 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:50.796053 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:50.796057 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:50.796061 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:50.796065 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:50.796069 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:50.796073 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:50.796077 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:50.796080 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:51.322364 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.css
[Fri Jun 17 12:14:51.322390 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:51.322393 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:51.322395 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:51.322397 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:51.322400 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:51.322402 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:51.322404 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:51.322406 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:51.322407 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:51.322409 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:51.331641 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/script.js
[Fri Jun 17 12:14:51.331665 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:51.331682 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:51.331687 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:51.331690 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:51.331694 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:51.331697 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:51.331700 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:51.331703 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:51.331705 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:51.331707 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:51.335361 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.extras.js
[Fri Jun 17 12:14:51.335379 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:51.335381 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:51.335384 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:51.335386 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:51.335388 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:51.335390 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:51.335392 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:51.335395 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:51.335397 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:51.335399 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:51.339538 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/js/bootstrap.min.js
[Fri Jun 17 12:14:51.339559 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:51.339561 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:51.339564 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:51.339567 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:51.339571 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:51.339574 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:51.339578 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:51.339582 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:51.339585 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:51.339588 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:51.343385 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/entete-web (1).png
[Fri Jun 17 12:14:51.343417 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:51.343420 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:51.343423 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:51.343425 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:51.343427 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:51.343429 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:51.343431 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:51.343433 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:51.343435 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:51.343437 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:51.347759 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.js
[Fri Jun 17 12:14:51.347787 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:51.347791 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:51.347795 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:51.347798 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:51.347802 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:51.347805 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:51.347809 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:51.347812 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:51.347816 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:51.347819 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:51.744911 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/stickUp2/build/js/stickUp.min.js
[Fri Jun 17 12:14:51.744932 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:51.744935 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:51.744937 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:51.744939 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:51.744941 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:51.744943 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:51.744946 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:51.744948 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:51.744949 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:51.744951 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:52.821042 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/script.js
[Fri Jun 17 12:14:52.821071 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:52.821074 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:52.821077 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:52.821079 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:52.821081 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:52.821083 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:52.821086 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:52.821088 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:52.821089 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:52.821091 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:52.827354 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/logoDojoClair.png
[Fri Jun 17 12:14:52.827374 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:52.827377 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:52.827379 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:52.827381 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:52.827383 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:52.827385 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:52.827387 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:52.827389 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:52.827391 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:52.827393 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:53.031348 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.js
[Fri Jun 17 12:14:53.031376 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:53.031379 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:53.031381 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:53.031384 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:53.031386 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:53.031388 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:53.031391 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:53.031393 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:53.031395 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:53.031408 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:53.167397 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.extras.js
[Fri Jun 17 12:14:53.167418 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:53.167421 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:53.167424 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:53.167427 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:53.167431 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:53.167434 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:53.167438 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:53.167441 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:53.167444 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:53.167447 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:53.306064 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.css
[Fri Jun 17 12:14:53.306088 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:53.306090 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:53.306093 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:53.306095 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:53.306097 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:53.306099 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:53.306101 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:53.306103 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:53.306105 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:53.306106 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:53.311426 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/entete-web (1).png
[Fri Jun 17 12:14:53.311448 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:53.311451 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:53.311453 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:53.311455 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:53.311457 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:53.311460 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:53.311462 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:53.311464 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:53.311475 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:53.311477 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:53.490411 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/logoDojoClair.png
[Fri Jun 17 12:14:53.490436 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:53.490440 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:53.490444 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:53.490447 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:53.490479 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:53.490482 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:53.490484 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:53.490486 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:53.490488 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:53.490491 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:58.715556 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/css/bootstrap.min.css
[Fri Jun 17 12:14:58.715594 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:58.715599 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:58.715603 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:58.715607 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:58.715611 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:58.715615 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:58.715619 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:58.715622 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:58.715626 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:58.715629 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:58.720799 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/font-awesome/css/font-awesome.min.css
[Fri Jun 17 12:14:58.720818 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:58.720821 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:58.720823 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:58.720826 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:58.720828 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:58.720830 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:58.720843 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:58.720846 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:58.720848 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:58.720850 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:58.723219 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/css/style.css
[Fri Jun 17 12:14:58.723234 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:58.723237 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:58.723240 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:58.723242 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:58.723244 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:58.723247 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:58.723249 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:58.723251 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:58.723253 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:58.723256 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:14:58.727307 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.css
[Fri Jun 17 12:14:58.727327 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:14:58.727330 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:14:58.727333 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:14:58.727335 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:14:58.727338 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:14:58.727340 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:14:58.727343 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:14:58.727345 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:14:58.727347 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:14:58.727349 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:38.883735 2016] [wsgi:error] [pid 3264] Not Found: /script
[Fri Jun 17 12:22:38.910020 2016] [wsgi:error] [pid 3264] Not Found: /jenkins/script
[Fri Jun 17 12:22:38.931551 2016] [wsgi:error] [pid 3264] Not Found: /login
[Fri Jun 17 12:22:38.957502 2016] [wsgi:error] [pid 3264] Not Found: /jmx-console
[Fri Jun 17 12:22:38.980829 2016] [wsgi:error] [pid 3264] Not Found: /manager/html
[Fri Jun 17 12:22:39.002186 2016] [wsgi:error] [pid 3264] Not Found: /msd
[Fri Jun 17 12:22:39.025173 2016] [wsgi:error] [pid 3264] Not Found: /mySqlDumper
[Fri Jun 17 12:22:39.041761 2016] [wsgi:error] [pid 3264] Not Found: /msd1.24stable
[Fri Jun 17 12:22:39.059675 2016] [wsgi:error] [pid 3264] Not Found: /msd1.24.4
[Fri Jun 17 12:22:39.076061 2016] [wsgi:error] [pid 3264] Not Found: /mysqldumper
[Fri Jun 17 12:22:39.101932 2016] [wsgi:error] [pid 3264] Not Found: /MySQLDumper
[Fri Jun 17 12:22:39.123945 2016] [wsgi:error] [pid 3264] Not Found: /mysql
[Fri Jun 17 12:22:39.154008 2016] [wsgi:error] [pid 3264] Not Found: /sql
[Fri Jun 17 12:22:39.180232 2016] [wsgi:error] [pid 3264] Not Found: /phpmyadmin
[Fri Jun 17 12:22:39.213834 2016] [wsgi:error] [pid 3264] Not Found: /phpMyAdmin
[Fri Jun 17 12:22:39.237359 2016] [wsgi:error] [pid 3264] Not Found: /mysql
[Fri Jun 17 12:22:39.255082 2016] [wsgi:error] [pid 3264] Not Found: /sql
[Fri Jun 17 12:22:39.286475 2016] [wsgi:error] [pid 3264] Not Found: /myadmin
[Fri Jun 17 12:22:39.306734 2016] [wsgi:error] [pid 3264] Not Found: /phpMyAdmin-4.2.1-all-languages
[Fri Jun 17 12:22:39.331425 2016] [wsgi:error] [pid 3264] Not Found: /phpMyAdmin-4.2.1-english
[Fri Jun 17 12:22:39.400187 2016] [wsgi:error] [pid 3264] Not Found: /sqlite/main.php
[Fri Jun 17 12:22:39.421654 2016] [wsgi:error] [pid 3264] Not Found: /SQLite/SQLiteManager-1.2.4/main.php
[Fri Jun 17 12:22:39.440976 2016] [wsgi:error] [pid 3264] Not Found: /SQLiteManager-1.2.4/main.php
[Fri Jun 17 12:22:39.469168 2016] [wsgi:error] [pid 3264] Not Found: /sqlitemanager/main.php
[Fri Jun 17 12:22:39.498692 2016] [wsgi:error] [pid 3264] Not Found: /SQlite/main.php
[Fri Jun 17 12:22:39.518127 2016] [wsgi:error] [pid 3264] Not Found: /SQLiteManager/main.php
[Fri Jun 17 12:22:41.773220 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/font-awesome/css/font-awesome.min.css
[Fri Jun 17 12:22:41.773263 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:41.773268 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:41.773272 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:41.773276 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:41.773280 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:41.773284 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:41.773288 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:41.773291 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:41.773294 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:41.773298 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:41.782008 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/jquery/dist/jquery.min.js
[Fri Jun 17 12:22:41.782168 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:41.782178 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:41.782184 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:41.782189 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:41.782195 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:41.782200 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:41.782205 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:41.782210 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:41.782215 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:41.782348 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:41.784116 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/js/bootstrap.min.js
[Fri Jun 17 12:22:41.784134 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:41.784137 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:41.784141 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:41.784144 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:41.784147 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:41.784151 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:41.784154 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:41.784157 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:41.784160 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:41.784163 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:41.788352 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/css/bootstrap.min.css
[Fri Jun 17 12:22:41.788378 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:41.788382 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:41.788386 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:41.788389 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:41.788393 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:41.788396 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:41.788399 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:41.788402 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:41.788405 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:41.788408 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:41.789844 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/stickUp2/build/js/stickUp.min.js
[Fri Jun 17 12:22:41.789869 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:41.789897 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:41.789903 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:41.789908 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:41.789914 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:41.789919 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:41.789924 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:41.789948 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:41.789954 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:41.789959 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:41.791589 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/css/style.css
[Fri Jun 17 12:22:41.791608 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:41.791612 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:41.791615 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:41.791618 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:41.791621 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:41.791624 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:41.791627 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:41.791630 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:41.791632 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:41.791635 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:42.276665 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.css
[Fri Jun 17 12:22:42.276690 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:42.276693 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:42.276696 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:42.276698 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:42.276700 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:42.276702 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:42.276704 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:42.276706 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:42.276708 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:42.276710 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:42.283229 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/script.js
[Fri Jun 17 12:22:42.283249 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:42.283252 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:42.283254 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:42.283256 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:42.283259 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:42.283261 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:42.283274 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:42.283277 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:42.283279 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:42.283281 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:42.287248 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.js
[Fri Jun 17 12:22:42.287265 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:42.287267 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:42.287270 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:42.287272 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:42.287274 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:42.287276 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:42.287278 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:42.287280 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:42.287282 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:42.287284 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:42.291275 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/js/bootstrap.min.js
[Fri Jun 17 12:22:42.291292 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:42.291295 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:42.291298 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:42.291300 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:42.291302 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:42.291304 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:42.291307 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:42.291309 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:42.291311 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:42.291312 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:42.295444 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/entete-web (1).png
[Fri Jun 17 12:22:42.295461 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:42.295463 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:42.295466 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:42.295468 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:42.295470 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:42.295485 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:42.295488 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:42.295490 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:42.295492 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:42.295494 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:42.303291 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.extras.js
[Fri Jun 17 12:22:42.303312 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:42.303315 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:42.303317 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:42.303319 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:42.303321 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:42.303324 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:42.303326 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:42.303328 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:42.303330 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:42.303332 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:42.689858 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/stickUp2/build/js/stickUp.min.js
[Fri Jun 17 12:22:42.689907 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:42.689910 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:42.689912 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:42.689914 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:42.689917 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:42.689919 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:42.689921 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:42.689923 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:42.689925 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:42.689927 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:42.771159 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/logoDojoClair.png
[Fri Jun 17 12:22:42.771185 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:42.771189 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:42.771192 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:42.771195 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:42.771216 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:42.771220 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:42.771223 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:42.771227 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:42.771230 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:42.771232 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:42.815702 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/script.js
[Fri Jun 17 12:22:42.815724 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:42.815726 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:42.815728 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:42.815731 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:42.815733 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:42.815735 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:42.815737 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:42.815739 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:42.815741 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:42.815742 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:42.960950 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.js
[Fri Jun 17 12:22:42.960980 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:42.960983 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:42.960985 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:42.960987 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:42.960990 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:42.960992 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:42.960994 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:42.960996 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:42.960998 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:42.961000 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:43.094338 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.extras.js
[Fri Jun 17 12:22:43.094365 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:43.094368 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:43.094371 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:43.094374 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:43.094390 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:43.094393 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:43.094396 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:43.094398 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:43.094400 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:43.094402 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:43.229106 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.css
[Fri Jun 17 12:22:43.229128 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:43.229131 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:43.229133 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:43.229135 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:43.229137 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:43.229139 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:43.229142 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:43.229144 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:43.229145 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:43.229147 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:43.235321 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/entete-web (1).png
[Fri Jun 17 12:22:43.235340 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:43.235342 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:43.235344 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:43.235346 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:43.235349 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:43.235351 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:43.235353 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:43.235355 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:43.235357 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:43.235359 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:22:43.440283 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/logoDojoClair.png
[Fri Jun 17 12:22:43.440315 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:22:43.440320 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:22:43.440323 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:22:43.440341 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:22:43.440344 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:22:43.440346 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:22:43.440348 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:22:43.440350 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:22:43.440352 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:22:43.440354 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:50.210858 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/css/bootstrap.min.css
[Fri Jun 17 12:24:50.210910 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:50.210914 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:50.210917 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:50.210920 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:50.210922 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:50.210925 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:50.210928 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:50.210930 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:50.210932 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:50.210934 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:50.215808 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/font-awesome/css/font-awesome.min.css
[Fri Jun 17 12:24:50.215835 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:50.215839 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:50.215843 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:50.215847 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:50.215852 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:50.215855 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:50.215859 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:50.215863 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:50.215867 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:50.215870 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:50.286222 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/css/style.css
[Fri Jun 17 12:24:50.286246 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:50.286250 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:50.286271 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:50.286274 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:50.286277 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:50.286279 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:50.286281 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:50.286283 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:50.286285 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:50.286287 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:50.287346 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/jquery/dist/jquery.min.js
[Fri Jun 17 12:24:50.287360 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:50.287363 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:50.287365 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:50.287368 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:50.287370 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:50.287372 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:50.287374 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:50.287376 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:50.287378 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:50.287380 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:50.291391 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/js/bootstrap.min.js
[Fri Jun 17 12:24:50.291410 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:50.291413 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:50.291415 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:50.291418 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:50.291420 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:50.291422 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:50.291425 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:50.291427 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:50.291429 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:50.291431 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:50.295480 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/stickUp2/build/js/stickUp.min.js
[Fri Jun 17 12:24:50.295518 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:50.295522 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:50.295525 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:50.295527 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:50.295532 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:50.295535 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:50.295537 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:50.295539 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:50.295542 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:50.295544 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:50.567945 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.css
[Fri Jun 17 12:24:50.567972 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:50.567975 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:50.567978 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:50.567980 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:50.567983 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:50.567985 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:50.567988 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:50.567990 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:50.567992 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:50.567994 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:50.575487 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/script.js
[Fri Jun 17 12:24:50.575514 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:50.575517 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:50.575520 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:50.575522 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:50.575525 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:50.575528 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:50.575531 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:50.575533 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:50.575535 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:50.575538 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:50.637157 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.js
[Fri Jun 17 12:24:50.637180 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:50.637183 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:50.637186 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:50.637188 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:50.637190 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:50.637193 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:50.637195 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:50.637197 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:50.637199 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:50.637201 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:50.662478 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.extras.js
[Fri Jun 17 12:24:50.667347 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:50.667377 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:50.667381 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:50.667383 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:50.667386 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:50.667388 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:50.667391 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:50.667393 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:50.667395 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:50.667398 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:50.692003 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/js/bootstrap.min.js
[Fri Jun 17 12:24:50.692026 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:50.692029 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:50.692032 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:50.692034 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:50.692037 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:50.692039 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:50.692042 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:50.692044 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:50.692046 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:50.692063 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:50.695450 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/entete-web (1).png
[Fri Jun 17 12:24:50.695473 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:50.695476 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:50.695479 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:50.695481 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:50.695484 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:50.695486 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:50.695489 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:50.695491 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:50.695493 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:50.695495 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:51.031491 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/stickUp2/build/js/stickUp.min.js
[Fri Jun 17 12:24:51.031516 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:51.031518 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:51.031521 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:51.031523 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:51.031525 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:51.031527 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:51.031529 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:51.031531 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:51.031533 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:51.031535 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:51.106395 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/logoDojoClair.png
[Fri Jun 17 12:24:51.106418 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:51.106421 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:51.106423 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:51.106426 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:51.106428 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:51.106430 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:51.106433 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:51.106435 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:51.106447 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:51.106469 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:51.161756 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/script.js
[Fri Jun 17 12:24:51.161778 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:51.161781 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:51.161784 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:51.161786 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:51.161788 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:51.161791 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:51.161793 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:51.161795 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:51.161797 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:51.161799 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:51.327536 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.js
[Fri Jun 17 12:24:51.327565 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:51.327570 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:51.327575 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:51.327579 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:51.327583 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:51.327587 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:51.327591 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:51.327594 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:51.327597 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:51.327601 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:51.463269 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.extras.js
[Fri Jun 17 12:24:51.463293 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:51.463296 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:51.463299 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:51.463302 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:51.463304 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:51.463307 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:51.463310 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:51.463326 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:51.463329 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:51.463331 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:51.684149 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.css
[Fri Jun 17 12:24:51.684172 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:51.684175 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:51.684178 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:51.684181 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:51.684183 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:51.684186 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:51.684188 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:51.684191 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:51.684193 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:51.684195 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:51.691639 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/entete-web (1).png
[Fri Jun 17 12:24:51.691670 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:51.691673 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:51.691676 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:51.691678 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:51.691681 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:51.691683 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:51.691686 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:51.691688 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:51.691691 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:51.691693 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:24:51.899439 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/logoDojoClair.png
[Fri Jun 17 12:24:51.899468 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:24:51.899472 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:24:51.899475 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:24:51.899477 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:24:51.899479 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:24:51.899482 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:24:51.899495 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:24:51.899498 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:24:51.899500 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:24:51.899502 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:55.472638 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/css/bootstrap.min.css
[Fri Jun 17 12:26:55.472691 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:55.472695 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:55.472700 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:55.472702 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:55.472705 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:55.472707 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:55.472711 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:55.472714 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:55.472716 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:55.472718 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:55.476251 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/css/style.css
[Fri Jun 17 12:26:55.476268 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:55.476271 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:55.476274 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:55.476276 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:55.476278 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:55.476281 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:55.476283 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:55.476285 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:55.476287 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:55.476289 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:55.480794 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/jquery/dist/jquery.min.js
[Fri Jun 17 12:26:55.480813 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:55.480816 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:55.480819 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:55.480822 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:55.480824 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:55.480843 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:55.480846 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:55.480848 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:55.480850 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:55.480852 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:55.483542 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/js/bootstrap.min.js
[Fri Jun 17 12:26:55.483558 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:55.483560 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:55.483563 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:55.483565 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:55.483567 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:55.483569 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:55.483573 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:55.483576 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:55.483590 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:55.483593 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:55.487377 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/stickUp2/build/js/stickUp.min.js
[Fri Jun 17 12:26:55.487395 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:55.487398 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:55.487400 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:55.487402 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:55.487405 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:55.487407 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:55.487409 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:55.487411 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:55.487413 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:55.487415 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:55.491468 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/font-awesome/css/font-awesome.min.css
[Fri Jun 17 12:26:55.491493 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:55.491496 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:55.491498 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:55.491500 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:55.491521 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:55.491524 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:55.491527 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:55.491529 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:55.491531 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:55.491533 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:55.976429 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.css
[Fri Jun 17 12:26:55.976464 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:55.976468 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:55.976472 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:55.976476 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:55.976479 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:55.976482 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:55.976486 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:55.976489 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:55.976492 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:55.976494 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:55.980887 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/script.js
[Fri Jun 17 12:26:55.980909 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:55.980912 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:55.980914 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:55.980917 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:55.980919 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:55.980921 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:55.980923 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:55.980925 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:55.980927 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:55.980929 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:55.983317 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.js
[Fri Jun 17 12:26:55.983338 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:55.983341 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:55.983343 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:55.983358 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:55.983361 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:55.983363 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:55.983365 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:55.983367 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:55.983368 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:55.983370 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:55.987868 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.extras.js
[Fri Jun 17 12:26:55.987899 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:55.987904 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:55.987908 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:55.987911 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:55.987915 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:55.987918 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:55.987921 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:55.987924 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:55.987927 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:55.987931 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:55.991402 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/bower_components/bootstrap/dist/js/bootstrap.min.js
[Fri Jun 17 12:26:55.991426 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:55.991429 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:55.991431 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:55.991434 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:55.991436 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:55.991438 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:55.991441 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:55.991443 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:55.991445 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:55.991447 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:55.995377 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/entete-web (1).png
[Fri Jun 17 12:26:55.995398 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:55.995400 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:55.995415 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:55.995418 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:55.995420 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:55.995422 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:55.995424 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:55.995426 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:55.995428 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:55.995430 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:56.407803 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/stickUp2/build/js/stickUp.min.js
[Fri Jun 17 12:26:56.407829 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:56.407832 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:56.407834 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:56.407836 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:56.407838 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:56.407840 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:56.407843 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:56.407845 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:56.407846 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:56.407848 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:56.465772 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/logoDojoClair.png
[Fri Jun 17 12:26:56.465790 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:56.465792 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:56.465795 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:56.465797 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:56.465799 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:56.465801 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:56.465803 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:56.465806 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:56.465807 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:56.465809 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:56.538559 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/js/script.js
[Fri Jun 17 12:26:56.538582 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:56.538597 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:56.538600 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:56.538602 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:56.538604 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:56.538606 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:56.538608 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:56.538610 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:56.538612 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:56.538614 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:56.674447 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.js
[Fri Jun 17 12:26:56.674490 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:56.674493 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:56.674495 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:56.674497 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:56.674499 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:56.674502 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:56.674504 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:56.674506 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:56.674507 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:56.674509 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:56.808781 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.extras.js
[Fri Jun 17 12:26:56.808808 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:56.808812 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:56.808815 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:56.808819 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:56.808822 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:56.808826 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:56.808829 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:56.808832 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:56.808836 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:56.808838 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:56.977794 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/leaflet/leaflet.css
[Fri Jun 17 12:26:56.977838 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:56.977843 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:56.977846 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:56.977849 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:56.977872 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:56.977878 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:56.977881 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:56.977884 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:56.977887 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:56.977895 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:56.983402 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/entete-web (1).png
[Fri Jun 17 12:26:56.983425 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:56.983427 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:56.983429 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:56.983432 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:56.983434 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:56.983436 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:56.983438 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:56.983440 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:56.983442 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:56.983443 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:26:57.170400 2016] [wsgi:error] [pid 3264] Internal Server Error: /static/img/logoDojoClair.png
[Fri Jun 17 12:26:57.170429 2016] [wsgi:error] [pid 3264] Traceback (most recent call last):
[Fri Jun 17 12:26:57.170432 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
[Fri Jun 17 12:26:57.170434 2016] [wsgi:error] [pid 3264]     response = self.process_exception_by_middleware(e, request)
[Fri Jun 17 12:26:57.170436 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
[Fri Jun 17 12:26:57.170439 2016] [wsgi:error] [pid 3264]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Fri Jun 17 12:26:57.170441 2016] [wsgi:error] [pid 3264]   File "/home/web/dojo_env/lib/python2.7/site-packages/django/views/static.py", line 54, in serve
[Fri Jun 17 12:26:57.170443 2016] [wsgi:error] [pid 3264]     fullpath = os.path.join(document_root, newpath)
[Fri Jun 17 12:26:57.170445 2016] [wsgi:error] [pid 3264]   File "/usr/lib/python2.7/posixpath.py", line 70, in join
[Fri Jun 17 12:26:57.170447 2016] [wsgi:error] [pid 3264]     elif path == '' or path.endswith('/'):
[Fri Jun 17 12:26:57.170469 2016] [wsgi:error] [pid 3264] AttributeError: 'NoneType' object has no attribute 'endswith'
[Fri Jun 17 12:27:24.954611 2016] [authz_core:error] [pid 3444] [client 80.13.157.88:56232] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:24.955065 2016] [authz_core:error] [pid 3446] [client 80.13.157.88:56234] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:24.956060 2016] [authz_core:error] [pid 3447] [client 80.13.157.88:56238] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:24.956751 2016] [authz_core:error] [pid 3445] [client 80.13.157.88:56236] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:24.957014 2016] [authz_core:error] [pid 3443] [client 80.13.157.88:56242] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:24.989681 2016] [authz_core:error] [pid 3444] [client 80.13.157.88:56232] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:24.991834 2016] [authz_core:error] [pid 3474] [client 80.13.157.88:56240] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:24.998814 2016] [authz_core:error] [pid 3446] [client 80.13.157.88:56234] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:25.001231 2016] [authz_core:error] [pid 3447] [client 80.13.157.88:56238] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:25.001955 2016] [authz_core:error] [pid 3445] [client 80.13.157.88:56236] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:25.002143 2016] [authz_core:error] [pid 3443] [client 80.13.157.88:56242] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:25.037040 2016] [authz_core:error] [pid 3443] [client 80.13.157.88:56242] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:25.075497 2016] [authz_core:error] [pid 3443] [client 80.13.157.88:56242] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:25.110746 2016] [authz_core:error] [pid 3443] [client 80.13.157.88:56242] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:25.151594 2016] [authz_core:error] [pid 3443] [client 80.13.157.88:56242] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:25.186872 2016] [authz_core:error] [pid 3443] [client 80.13.157.88:56242] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:25.222294 2016] [authz_core:error] [pid 3443] [client 80.13.157.88:56242] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:25.259803 2016] [authz_core:error] [pid 3443] [client 80.13.157.88:56242] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:25.260480 2016] [authz_core:error] [pid 3445] [client 80.13.157.88:56236] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:27:25.303011 2016] [authz_core:error] [pid 3445] [client 80.13.157.88:56236] AH01630: client denied by server configuration: /home/web/dojoentreprisesagiles.fr, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.097794 2016] [authz_core:error] [pid 3564] [client 80.13.157.88:56244] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.098139 2016] [authz_core:error] [pid 3563] [client 80.13.157.88:56250] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.098894 2016] [authz_core:error] [pid 3567] [client 80.13.157.88:56248] AH01630: client denied by server configuration: /home/web/dojo_env/staticcss, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.099879 2016] [authz_core:error] [pid 3566] [client 80.13.157.88:56254] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.100691 2016] [authz_core:error] [pid 3565] [client 80.13.157.88:56252] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.101720 2016] [authz_core:error] [pid 3594] [client 80.13.157.88:56246] AH01630: client denied by server configuration: /home/web/dojo_env/staticjs, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.133053 2016] [authz_core:error] [pid 3564] [client 80.13.157.88:56244] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.133266 2016] [authz_core:error] [pid 3563] [client 80.13.157.88:56250] AH01630: client denied by server configuration: /home/web/dojo_env/staticjs, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.133536 2016] [authz_core:error] [pid 3567] [client 80.13.157.88:56248] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.134621 2016] [authz_core:error] [pid 3566] [client 80.13.157.88:56254] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.137563 2016] [authz_core:error] [pid 3594] [client 80.13.157.88:56246] AH01630: client denied by server configuration: /home/web/dojo_env/staticimg, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.172454 2016] [authz_core:error] [pid 3565] [client 80.13.157.88:56252] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.172844 2016] [authz_core:error] [pid 3594] [client 80.13.157.88:56246] AH01630: client denied by server configuration: /home/web/dojo_env/staticimg, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.210116 2016] [authz_core:error] [pid 3594] [client 80.13.157.88:56246] AH01630: client denied by server configuration: /home/web/dojo_env/staticjs, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.251414 2016] [authz_core:error] [pid 3594] [client 80.13.157.88:56246] AH01630: client denied by server configuration: /home/web/dojo_env/staticjs, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.286686 2016] [authz_core:error] [pid 3594] [client 80.13.157.88:56246] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.322253 2016] [authz_core:error] [pid 3594] [client 80.13.157.88:56246] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.359183 2016] [authz_core:error] [pid 3594] [client 80.13.157.88:56246] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.360072 2016] [authz_core:error] [pid 3565] [client 80.13.157.88:56252] AH01630: client denied by server configuration: /home/web/dojo_env/staticimg, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:51.396656 2016] [authz_core:error] [pid 3565] [client 80.13.157.88:56252] AH01630: client denied by server configuration: /home/web/dojo_env/staticimg, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:55.943756 2016] [authz_core:error] [pid 3565] [client 80.13.157.88:56252] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:55.947158 2016] [authz_core:error] [pid 3594] [client 80.13.157.88:56246] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:55.947401 2016] [authz_core:error] [pid 3566] [client 80.13.157.88:56254] AH01630: client denied by server configuration: /home/web/dojo_env/staticcss, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:28:55.947853 2016] [authz_core:error] [pid 3567] [client 80.13.157.88:56248] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:31.069013 2016] [authz_core:error] [pid 3563] [client 80.13.157.88:56264] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:31.102959 2016] [authz_core:error] [pid 3563] [client 80.13.157.88:56264] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:31.112088 2016] [authz_core:error] [pid 3564] [client 80.13.157.88:56266] AH01630: client denied by server configuration: /home/web/dojo_env/staticcss, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:31.118272 2016] [authz_core:error] [pid 3594] [client 80.13.157.88:56270] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:31.118876 2016] [authz_core:error] [pid 3598] [client 80.13.157.88:56268] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:31.120035 2016] [authz_core:error] [pid 3599] [client 80.13.157.88:56272] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:31.120588 2016] [authz_core:error] [pid 3567] [client 80.13.157.88:56274] AH01630: client denied by server configuration: /home/web/dojo_env/staticjs, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:31.137488 2016] [authz_core:error] [pid 3563] [client 80.13.157.88:56264] AH01630: client denied by server configuration: /home/web/dojo_env/staticjs, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:31.147007 2016] [authz_core:error] [pid 3564] [client 80.13.157.88:56266] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:31.163288 2016] [authz_core:error] [pid 3594] [client 80.13.157.88:56270] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:31.165963 2016] [authz_core:error] [pid 3567] [client 80.13.157.88:56274] AH01630: client denied by server configuration: /home/web/dojo_env/staticimg, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:31.217513 2016] [authz_core:error] [pid 3567] [client 80.13.157.88:56274] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:31.220189 2016] [authz_core:error] [pid 3594] [client 80.13.157.88:56270] AH01630: client denied by server configuration: /home/web/dojo_env/staticimg, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:32.321830 2016] [authz_core:error] [pid 3594] [client 80.13.157.88:56270] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:32.322417 2016] [authz_core:error] [pid 3567] [client 80.13.157.88:56274] AH01630: client denied by server configuration: /home/web/dojo_env/staticcss, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:32.323439 2016] [authz_core:error] [pid 3564] [client 80.13.157.88:56266] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:32.323936 2016] [authz_core:error] [pid 3563] [client 80.13.157.88:56264] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:32.324392 2016] [authz_core:error] [pid 3599] [client 80.13.157.88:56272] AH01630: client denied by server configuration: /home/web/dojo_env/staticjs, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:32.324642 2016] [authz_core:error] [pid 3598] [client 80.13.157.88:56268] AH01630: client denied by server configuration: /home/web/dojo_env/staticjs, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:32.532930 2016] [authz_core:error] [pid 3567] [client 80.13.157.88:56274] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:32.533359 2016] [authz_core:error] [pid 3564] [client 80.13.157.88:56266] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:32.533936 2016] [authz_core:error] [pid 3563] [client 80.13.157.88:56264] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:32.534149 2016] [authz_core:error] [pid 3598] [client 80.13.157.88:56268] AH01630: client denied by server configuration: /home/web/dojo_env/staticimg, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:32.846232 2016] [authz_core:error] [pid 3598] [client 80.13.157.88:56268] AH01630: client denied by server configuration: /home/web/dojo_env/staticimg, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:35.047731 2016] [authz_core:error] [pid 3598] [client 80.13.157.88:56268] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:35.397262 2016] [authz_core:error] [pid 3598] [client 80.13.157.88:56268] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:35.399370 2016] [authz_core:error] [pid 3566] [client 80.13.157.88:56278] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:35.399714 2016] [authz_core:error] [pid 3597] [client 80.13.157.88:56276] AH01630: client denied by server configuration: /home/web/dojo_env/staticcss, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:35.497869 2016] [authz_core:error] [pid 3598] [client 80.13.157.88:56268] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:35.611273 2016] [authz_core:error] [pid 3597] [client 80.13.157.88:56276] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:35.645114 2016] [authz_core:error] [pid 3600] [client 80.13.157.88:56280] AH01630: client denied by server configuration: /home/web/dojo_env/staticjs, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:35.683388 2016] [authz_core:error] [pid 3563] [client 80.13.157.88:56282] AH01630: client denied by server configuration: /home/web/dojo_env/staticjs, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:35.683733 2016] [authz_core:error] [pid 3594] [client 80.13.157.88:56284] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:35.683959 2016] [authz_core:error] [pid 3598] [client 80.13.157.88:56268] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:35.684635 2016] [authz_core:error] [pid 3597] [client 80.13.157.88:56276] AH01630: client denied by server configuration: /home/web/dojo_env/staticimg, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:36.120197 2016] [authz_core:error] [pid 3597] [client 80.13.157.88:56276] AH01630: client denied by server configuration: /home/web/dojo_env/staticimg, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:38.160866 2016] [authz_core:error] [pid 3566] [client 80.13.157.88:56278] AH01630: client denied by server configuration: /home/web/dojo_env/staticbower_components, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:38.271615 2016] [authz_core:error] [pid 3566] [client 80.13.157.88:56278] AH01630: client denied by server configuration: /home/web/dojo_env/staticjs, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:38.314388 2016] [authz_core:error] [pid 3566] [client 80.13.157.88:56278] AH01630: client denied by server configuration: /home/web/dojo_env/staticjs, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:38.353065 2016] [authz_core:error] [pid 3566] [client 80.13.157.88:56278] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:38.389395 2016] [authz_core:error] [pid 3566] [client 80.13.157.88:56278] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:38.430398 2016] [authz_core:error] [pid 3566] [client 80.13.157.88:56278] AH01630: client denied by server configuration: /home/web/dojo_env/staticleaflet, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:38.430795 2016] [authz_core:error] [pid 3597] [client 80.13.157.88:56276] AH01630: client denied by server configuration: /home/web/dojo_env/staticimg, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:29:38.473325 2016] [authz_core:error] [pid 3597] [client 80.13.157.88:56276] AH01630: client denied by server configuration: /home/web/dojo_env/staticimg, referer: http://vps290046.ovh.net/
[Fri Jun 17 12:30:49.625163 2016] [authz_core:error] [pid 3664] [client 80.13.157.88:56298] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/b6ddc9a60d.jpg, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.661073 2016] [authz_core:error] [pid 3664] [client 80.13.157.88:56298] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/ade410d55c.jpg, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.665981 2016] [authz_core:error] [pid 3663] [client 80.13.157.88:56300] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/954777340a.jpg, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.666192 2016] [authz_core:error] [pid 3665] [client 80.13.157.88:56302] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/9c8574f8fb.jpg, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.666794 2016] [authz_core:error] [pid 3690] [client 80.13.157.88:56308] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/cc15ceedae.jpg, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.667031 2016] [authz_core:error] [pid 3666] [client 80.13.157.88:56304] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/e6038a9a9e.jpg, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.667653 2016] [authz_core:error] [pid 3697] [client 80.13.157.88:56306] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/9e285703fb.png, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.698144 2016] [authz_core:error] [pid 3664] [client 80.13.157.88:56298] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/3f5b4c87bf.jpg, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.706573 2016] [authz_core:error] [pid 3697] [client 80.13.157.88:56306] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/0add0b2305.png, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.801603 2016] [authz_core:error] [pid 3697] [client 80.13.157.88:56306] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/b6ddc9a60d.jpg, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.801959 2016] [authz_core:error] [pid 3664] [client 80.13.157.88:56298] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/ade410d55c.jpg, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.802513 2016] [authz_core:error] [pid 3666] [client 80.13.157.88:56304] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/954777340a.jpg, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.803230 2016] [authz_core:error] [pid 3690] [client 80.13.157.88:56308] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/9c8574f8fb.jpg, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.803433 2016] [authz_core:error] [pid 3665] [client 80.13.157.88:56302] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/e6038a9a9e.jpg, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.804245 2016] [authz_core:error] [pid 3663] [client 80.13.157.88:56300] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/9e285703fb.png, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.846431 2016] [authz_core:error] [pid 3663] [client 80.13.157.88:56300] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/cc15ceedae.jpg, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.846681 2016] [authz_core:error] [pid 3665] [client 80.13.157.88:56302] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/3f5b4c87bf.jpg, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 12:30:49.847267 2016] [authz_core:error] [pid 3690] [client 80.13.157.88:56308] AH01630: client denied by server configuration: /home/web/dojo_env/dojo_entreprises_agiles_env/media/mugshots/0add0b2305.png, referer: http://vps290046.ovh.net/portrait
[Fri Jun 17 14:58:15.095076 2016] [wsgi:error] [pid 4188] /home/web/dojo_env/src/django-timelinejs-master/timelinejs/models.py:5: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
[Fri Jun 17 14:58:15.095150 2016] [wsgi:error] [pid 4188]   class ListField(models.TextField):
[Fri Jun 17 14:58:15.095153 2016] [wsgi:error] [pid 4188] 
[Fri Jun 17 14:58:15.141667 2016] [wsgi:error] [pid 4188] /home/web/dojo_env/dojo_entreprises_agiles_env/mon_site/urls.py:31: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got userena.views.signup). Pass the callable instead.
[Fri Jun 17 14:58:15.141695 2016] [wsgi:error] [pid 4188]   ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
[Fri Jun 17 14:58:15.141698 2016] [wsgi:error] [pid 4188] 
[Fri Jun 17 14:58:15.145055 2016] [wsgi:error] [pid 4188] Forbidden (CSRF token missing or incorrect.): /accounts/signin/
